Data processing

In [39]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score

In [40]:
dataset = pd.read_csv("Bank_data.csv")

In [41]:
dataset.head()

User ID  Gender  Age  Salary  Purchased
0  15624510    Male   19   19000          0
1  15810944    Male   35   20000          0
2  15668575  Female   26   43000          0
3  15603246  Female   27   57000          0
4  15804002    Male   19   76000          0

In [42]:
x = dataset.iloc[:,2:4].values

In [43]:
y = dataset.iloc[:,-1].values

Splitting dataset

In [44]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 0)

Feature scaling

In [45]:
standardscaler = StandardScaler()
x_train = standardscaler.fit_transform(x_train)
x_test = standardscaler.transform(x_test)

Training model

In [46]:
classifier = LogisticRegression()

In [47]:
classifier.fit(x_train,y_train)

LogisticRegression()

In [48]:
classifier.intercept_

array([-0.87076381])

In [49]:
classifier.coef_

array([[2.00316198, 1.08088613]])

In [50]:
standardscaler.transform([[30,80000]])

array([[-0.79895082,  0.29180308]])

Predicting a result

In [51]:
classifier.predict(standardscaler.transform([[30,80000]]))

array([0])

Predicting test result

In [52]:
yPrediction = classifier.predict(x_test)

In [53]:
print(yPrediction)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1]


In [54]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [55]:
df = pd.DataFrame()
df['y_test'] = y_test
df['yPrediction'] = yPrediction
df['diffrence'] = y_test - yPrediction

In [56]:
df

y_test  yPrediction  diffrence
0        0            0          0
1        0            0          0
2        0            0          0
3        0            0          0
4        0            0          0
..     ...          ...        ...
75       0            0          0
76       0            1         -1
77       0            0          0
78       1            1          0
79       1            1          0

[80 rows x 3 columns]

Confusion matrix

In [57]:
confusionmatrix = confusion_matrix(y_test,yPrediction)

In [58]:
print(confusionmatrix)

[[57  1]
 [ 5 17]]


In [59]:
acc = accuracy_score(y_test,yPrediction)

In [60]:
print('Accuracy of the model is {}%'.format( acc*100))

Accuracy of the model is 92.5%
