Data processing

In [24]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score

In [25]:
dataset = pd.read_csv("Bank_data.csv")

In [26]:
dataset.head()

User ID  Gender  Age  Salary  Purchased
0  15624510    Male   19   19000          0
1  15810944    Male   35   20000          0
2  15668575  Female   26   43000          0
3  15603246  Female   27   57000          0
4  15804002    Male   19   76000          0

In [27]:
x = dataset.iloc[:,2:4].values

In [28]:
y = dataset.iloc[:,-1].values

Splitting dataset

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 0)

Feature scaling

In [30]:
standardscaler = StandardScaler()
x_train = standardscaler.fit_transform(x_train)
x_test = standardscaler.transform(x_test)

Training model

In [31]:
classifier = KNeighborsClassifier( n_neighbors=5, p= 2, metric= "minkowski")

In [32]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [33]:
standardscaler.transform([[30,80000]])

array([[-0.79895082,  0.29180308]])

Predicting a new result

In [34]:

classifier.predict(standardscaler.transform([[30,80000]]))

array([0])

In [35]:
yPrediction = classifier.predict(x_test)

In [36]:
print(yPrediction)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [37]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [38]:
df = pd.DataFrame()
df['y_test'] = y_test
df['yPrediction'] = yPrediction
df['diffrence'] = y_test - yPrediction

In [39]:
df

y_test  yPrediction  diffrence
0        0            0          0
1        0            0          0
2        0            0          0
3        0            0          0
4        0            0          0
..     ...          ...        ...
75       0            0          0
76       0            0          0
77       0            0          0
78       1            1          0
79       1            1          0

[80 rows x 3 columns]

Confusion Matrix

In [40]:
confusionmatrix = confusion_matrix(y_test,yPrediction)

In [41]:
print(confusionmatrix)

[[55  3]
 [ 1 21]]


In [42]:
acc = accuracy_score(y_test,yPrediction)

In [43]:
print('Accuracy of the model is {}%'.format( acc*100))

Accuracy of the model is 95.0%
