Data Processing

In [25]:
#Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [26]:
#Importing dataset
dataset = pd.read_csv("restaurant_profit.csv")

In [27]:
dataset.head()

Miscellaneous Expenses  Food Innovation  Advertisement     City     Profit
0               138671.80        167497.20      475918.10  Chicago  202443.83
1               153151.59        164745.70      448032.53   Mumbai  201974.06
2               102919.55        155589.51      412068.54    Tokyo  201232.39
3               120445.85        146520.41      387333.62  Chicago  193083.99
4                93165.77        144255.34      370302.42    Tokyo  176369.94

In [28]:
x = dataset.iloc[: , 0:-1].values

In [29]:
y = dataset.iloc[: , -1].values

Encoding categorical data

In [30]:
columnT = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(columnT.fit_transform(x))

In [31]:
x

array([[1.0, 0.0, 0.0, 138671.8, 167497.2, 475918.1],
       [0.0, 1.0, 0.0, 153151.59, 164745.7, 448032.53],
       [0.0, 0.0, 1.0, 102919.55, 155589.51, 412068.54],
       [1.0, 0.0, 0.0, 120445.85, 146520.41, 387333.62],
       [0.0, 0.0, 1.0, 93165.77, 144255.34, 370302.42],
       [1.0, 0.0, 0.0, 101588.71, 134024.9, 366995.36],
       [0.0, 1.0, 0.0, 148972.87, 136763.46, 131850.82],
       [0.0, 0.0, 1.0, 147304.06, 132446.13, 328010.68],
       [1.0, 0.0, 0.0, 150492.95, 122690.52, 315747.29],
       [0.0, 1.0, 0.0, 110453.17, 125482.88, 309115.62],
       [0.0, 0.0, 1.0, 112368.11, 104061.08, 233294.95],
       [0.0, 1.0, 0.0, 93564.61, 102819.96, 253878.55],
       [0.0, 0.0, 1.0, 129094.38, 96011.75, 253973.44],
       [0.0, 1.0, 0.0, 137269.07, 94140.39, 256798.93],
       [0.0, 0.0, 1.0, 158321.42, 122091.24, 260646.92],
       [1.0, 0.0, 0.0, 124390.84, 116671.61, 265910.23],
       [0.0, 1.0, 0.0, 123371.55, 80161.11, 268480.06],
       [1.0, 0.0, 0.0, 146851.58, 96805.1

Splitting the dataset

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

Training the model

In [33]:
linearR = LinearRegression()

In [34]:
linearR.fit(x_train, y_train)

LinearRegression()

Predicting the test set results

In [35]:
yPrediction = linearR.predict(x_test)

In [36]:
yPrediction

array([113197.20159798, 142764.27760812, 142629.73845172,  82158.09851261,
       188719.48221047, 126343.24230165,  78033.6920968 , 108973.7337469 ,
       124151.43533011, 178103.06569543])

In [37]:
y_test

array([113464.38, 154441.4 , 156303.95,  87980.83, 201232.39, 115190.31,
        91411.06, 107665.56, 120534.25, 176369.94])

In [38]:
df = pd.DataFrame()
df["y_actual"] = y_test 
df["yPrediction"] = yPrediction
print(df)

    y_actual    yPrediction
0  113464.38  113197.201598
1  154441.40  142764.277608
2  156303.95  142629.738452
3   87980.83   82158.098513
4  201232.39  188719.482210
5  115190.31  126343.242302
6   91411.06   78033.692097
7  107665.56  108973.733747
8  120534.25  124151.435330
9  176369.94  178103.065695
