Data processing

In [2]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score

In [3]:
dataset = pd.read_csv("Bank_data.csv")

In [4]:
dataset.head()

User ID  Gender  Age  Salary  Purchased
0  15624510    Male   19   19000          0
1  15810944    Male   35   20000          0
2  15668575  Female   26   43000          0
3  15603246  Female   27   57000          0
4  15804002    Male   19   76000          0

In [5]:
x = dataset.iloc[:,2:4].values

In [6]:
y = dataset.iloc[:,-1].values

Splitting dataset

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 0)

Feature scaling

In [8]:
standardscaler = StandardScaler()
x_train = standardscaler.fit_transform(x_train)
x_test = standardscaler.transform(x_test)

Training model

In [9]:
classifier = RandomForestClassifier( n_estimators=10, criterion="entropy",random_state= 0)

In [10]:
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [11]:
standardscaler.transform([[30,80000]])

array([[-0.79895082,  0.29180308]])

Predicting a new result

In [12]:

classifier.predict(standardscaler.transform([[30,80000]]))

array([0])

In [13]:
yPrediction = classifier.predict(x_test)

In [14]:
print(yPrediction)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1
 0 0 0 0 1 1]


In [15]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


In [16]:
df = pd.DataFrame()
df['y_test'] = y_test
df['yPrediction'] = yPrediction
df['diffrence'] = y_test - yPrediction

In [17]:
df

y_test  yPrediction  diffrence
0        0            0          0
1        0            0          0
2        0            0          0
3        0            0          0
4        0            0          0
..     ...          ...        ...
75       0            0          0
76       0            0          0
77       0            0          0
78       1            1          0
79       1            1          0

[80 rows x 3 columns]

Confusion Matrix

In [18]:
confusionmatrix = confusion_matrix(y_test,yPrediction)

In [19]:
print(confusionmatrix)

[[54  4]
 [ 3 19]]


In [20]:
acc = accuracy_score(y_test,yPrediction)

In [21]:
print('Accuracy of the model is {}%'.format( acc*100))

Accuracy of the model is 91.25%
